In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np


In [2]:
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
train_ds = tf.keras.utils.image_dataset_from_directory(
    r"E:\ml\projects\dataset\lukemia_data\train",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical", 
    shuffle=True
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    r"E:\ml\projects\dataset\lukemia_data\val",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical",
    shuffle=False
)



Found 2277 files belonging to 4 classes.
Found 486 files belonging to 4 classes.


In [3]:
class_names = train_ds.class_names
print(class_names)

['Benign', 'Early', 'Pre', 'Pro']


In [4]:
num_classes=4
model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),

    layers.Conv2D(32, (3,3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),


    layers.MaxPooling2D(),
    layers.Conv2D(64, (3,3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),


    layers.MaxPooling2D(),
    layers.Conv2D(128, (3,3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),


    layers.MaxPooling2D(),
    layers.Conv2D(256, (3,3), padding='same'),
    layers.BatchNormalization(),
    layers.Activation('relu'),

    
    layers.MaxPooling2D(),
    layers.GlobalAveragePooling2D(),
    
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(num_classes, activation='softmax')
])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 224, 224, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 224, 224, 32)        │             128 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation (Activation)              │ (None, 224, 224, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 112, 112, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 112, 112, 64)        │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 112, 112, 64)        │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_1 (Activation)            │ (None, 112, 112, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 56, 56, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 56, 56, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 56, 56, 128)         │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_2 (Activation)            │ (None, 56, 56, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 28, 28, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 28, 28, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_3                │ (None, 28, 28, 256)         │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_3 (Activation)            │ (None, 28, 28, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 14, 14, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ global_average_pooling2d             │ (None, 256)                 │               0 │
│ (GlobalAveragePooling2D)             │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │              

 Total params: 423,748 (1.62 MB)

 Trainable params: 422,788 (1.61 MB)

 Non-trainable params: 960 (3.75 KB)

In [5]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [6]:
model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=40,
   
)


Epoch 1/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 158s 2s/step - accuracy: 0.7387 - loss: 0.7089 - val_accuracy: 0.1564 - val_loss: 1.7903
Epoch 2/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 158s 2s/step - accuracy: 0.9188 - loss: 0.2830 - val_accuracy: 0.5782 - val_loss: 1.6719
Epoch 3/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 167s 2s/step - accuracy: 0.9495 - loss: 0.1827 - val_accuracy: 0.4259 - val_loss: 2.7046
Epoch 4/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 212s 2s/step - accuracy: 0.9635 - loss: 0.1436 - val_accuracy: 0.8827 - val_loss: 0.4155
Epoch 5/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 179s 2s/step - accuracy: 0.9657 - loss: 0.1203 - val_accuracy: 0.6975 - val_loss: 1.1865
Epoch 6/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 178s 2s/step - accuracy: 0.9693 - loss: 0.1124 - val_accuracy: 0.9815 - val_loss: 0.0982
Epoch 7/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 206s 3s/step - accuracy: 0.9763 - loss: 0.0837 - val_accuracy: 0.8292 - val_loss: 0.4144
Epoch 8/40
72/72 ━━━━━━━━━━━━━━━━━━━━ 206s 3s/step - accuracy: 0.9824 - loss: 0.0786 - val_accuracy: 0.9733 - v

In [10]:
test_ds = tf.keras.utils.image_dataset_from_directory(
    r"E:\ml\projects\dataset\lukemia_data\test",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode="categorical", 
    shuffle=False
)
class_names = test_ds.class_names
print(class_names)

Found 493 files belonging to 4 classes.
['Benign', 'Early', 'Pre', 'Pro']


In [36]:
y_true = np.concatenate([y.numpy() for _, y in test_ds])
y_true=np.argmax(y_true,axis=1)
y_pred = model.predict(test_ds)
y_pred = np.argmax(y_pred, axis=1)


16/16 ━━━━━━━━━━━━━━━━━━━━ 6s 375ms/step


In [47]:
from sklearn.metrics import recall_score,f1_score, confusion_matrix,accuracy_score
print("Accuracy:",accuracy_score(y_true,y_pred))
print("confusion matrix:\n",confusion_matrix(y_true,y_pred))
print("recall:",recall_score(y_true,y_pred,average="macro"))
print("f1 score:",f1_score(y_true,y_pred,average="macro"))

Accuracy: 0.9979716024340771
confusion matrix:
 [[ 77   0   0   0]
 [  0 149   0   0]
 [  0   0 145   0]
 [  1   0   0 121]]
recall: 0.9979508196721312
f1 score: 0.9973582901898315
